This patch just fixes an annoyance when calling our script without any argument.
git-svn-id: svn+ssh://common-lisp.net/project/clfswm/svn/clfswm@48 a42fa774-7830-0410-a598-a0bf735cded7

diff --git a/contrib/clfswm b/contrib/clfswm
--- a/contrib/clfswm
+++ b/contrib/clfswm
@@ -103,9 +103,6 @@ do
     shift
 done
 
-test -x $(type -p $lisp) || die "$lisp can't be found."
-test -e $clfswm_asd_path/clfswm.asd || die "can't find clfswm.asd in $clfswm_asd_path"
-test -e $asdf_path/asdf.lisp || die "can't find asdf.lisp in $asdf_path"
 
 dump_image="$dump_path/clfswm-$(cksum $(type -p $lisp) | cut -d ' ' -f 1).core"
 
@@ -120,7 +117,11 @@ if test ! -e "$dump_image" ||
         do  test "$dump_image" -ot "$i" && exit 1
         done )
 then
-	eval build_$lisp
+    test -x $(type -p $lisp) || die "$lisp can't be found."
+    test -e $clfswm_asd_path/clfswm.asd || die "can't find clfswm.asd in $clfswm_asd_path"
+    test -e $asdf_path/asdf.lisp || die "can't find asdf.lisp in $asdf_path"
+
+    eval build_$lisp
 fi
 
 # Run the resulting image
